stages:
 - build

variables:
 GIT_SUBMODULE_STRATEGY: recursive

sample:
 stage: build
 script:
 - cmd /C %CI_PROJECT_DIR%\src\sample\gradlew.bat -p %CI_PROJECT_DIR%\src\sample assembleDebug
 - copy src\sample\build\outputs\apk\sample-debug.apk sample.apk
 tags:
 - android
 only:
 - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
 artifacts:
  name: "sample"
  paths:
  - sample.apk

sample-test:
 stage: build
 script:
 - cmd /C %CI_PROJECT_DIR%\src\sample\gradlew.bat -p %CI_PROJECT_DIR%\src\sample assembleDebug
 - copy src\sample\build\outputs\apk\sample-debug.apk sample.apk
 tags:
 - android
 only:
 - /test\/sample\/.*/
 artifacts:
  name: "sample"
  expire_in: 1 week
  paths:
  - sample.apk
